spring:
  application:
    name: api

  security:
    user:
      name: admin # temp
      password: admin # temp

management:
  endpoints:
    health:
      show-details: when-authorized
logging:
  level:
    org.springframework.data.neo4j.cypher: DEBUG
